# -*- mode: sh; -*-

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
# with direnv
# https://github.com/romkatv/powerlevel10k#how-do-i-initialize-direnv-when-using-instant-prompt
(( ${+commands[direnv]} )) && emulate zsh -c "$(direnv export zsh)"

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

(( ${+commands[direnv]} )) && emulate zsh -c "$(direnv hook zsh)"

# Extra config (specific PATH or enviromnent variables).
if [ -f ~/.extra ]; then
    source ~/.extra
fi

# Extra dependencies.
if [ -d ~/.external-foggy ]; then
    source ~/.external-foggy/init.zsh
fi

source ~/.zprezto/init.zsh

# Word Bash style (only alphanu chars)
autoload -U select-word-style
select-word-style bash

bindkey '^[[1;5C' forward-word  # [Ctrl-RightArrow] - move forward one word
bindkey '^[[1;5D' backward-word # [Ctrl-LeftArrow] - move backward one word
bindkey '^[[3;5~' kill-word     # [Crtl-Delete] - kill word

# Some aliases.
if [ -f ~/.aliases ]; then
    source ~/.aliases
fi

# Some shell functions.
if [ -f ~/.functions ]; then
    source ~/.functions
fi

# Some functions dedicated to zsh.
if [ -f ~/.functions.zsh ]; then
    source ~/.functions.zsh
fi


# For direnv (http://direnv.net/).
[[ -x `which direnv` ]] && eval "$(direnv hook zsh)"

# Pew complete & prompt (Python virtual env)
if [[ -x `which pew` ]]; then
    source $(pew shell_config)
fi

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/dag/.sdkman"
[[ -s "/home/dag/.sdkman/bin/sdkman-init.sh" ]] && source "/home/dag/.sdkman/bin/sdkman-init.sh"

# PATH="$HOME/perl5/bin${PATH:+:${PATH}}"; export PATH;
# PERL5LIB="$HOME/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
# PERL_LOCAL_LIB_ROOT="$HOME/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
# PERL_MB_OPT="--install_base \"$HOME/perl5\""; export PERL_MB_OPT;
# PERL_MM_OPT="INSTALL_BASE=$HOME/perl5"; export PERL_MM_OPT;

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
