# -*- mode: sh; -*-

# Extra config (specific PATH or enviromnent variables).
if [ -f ~/.extra ]; then
    source ~/.extra
fi

source ~/.zprezto/init.zsh

bindkey '^[[1;5C' forward-word  # [Ctrl-RightArrow] - move forward one word
bindkey '^[[1;5D' backward-word # [Ctrl-LeftArrow] - move backward one word

# Some aliases.
if [ -f ~/.aliases ]; then
    source ~/.aliases
fi

# Some functions.
if [ -f ~/.functions ]; then
    source ~/.functions
fi

# Extra dependencies.
if [ -d ~/.external-foggy ]; then
    source ~/.external-foggy/init.zsh
fi

# For direnv (http://direnv.net/).
[[ -x `which direnv` ]] && eval "$(direnv hook zsh)"
