# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Oh-my-zsh plugins.
plugins=(git mercurial zshmarks)

source $ZSH/oh-my-zsh.sh
ZSH_THEME_TERM_TITLE_IDLE="%2d"


# Set up the prompt
autoload -Uz promptinit
promptinit

# Some colors.
fg_pink=$'\e[1;35m'
#Attributes
at_normal=$'\e[0m'
at_bold=$'\e[1m'

# Looks like '@host [time] current dir '
PROMPT="%{$bg_bold[blue]%}@%m$reset_color ${fg_pink}${at_bold}⌚ %T${at_normal} ${fg_gray}${at_bold}%~$reset_color
▶ "
# RPROMPT="${fg_lblue}[%T]${at_normal}"


# If use 'powerline'
#if [ -f ~/code/powerline/powerline/bindings/bash/powerline.sh ]; then
#    source ~/code/powerline/powerline/bindings/zsh/powerline.zsh
#fi

setopt histignorealldups sharehistory
# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# Some aliases.
if [ -f ~/.aliases ]; then
    source ~/.aliases
fi

# Extra config.
if [ -f ~/.extra ]; then
    source ~/.extra
fi
