#+TITLE: README
#+AUTHOR: Damien Garaud

"FoggyCowInn" comes from "FogCowInn", an anagram of "own config". You have
theses following directories:

- =dotfiles=: generic "rc" configuration files for bash, zsh, git, mercurial, etc.
- =emacs=: a few Emacs Lisp files to configure my Emacs 24 environment.
- =ipython=: store a IPython configuration and different profiles.

* dotfiles

  Several configuration files for Zsh, Git, Mercurial, etc.

  See the [[https://github.com/garaud/foggycowinn/blob/master/dotfiles/README.org][dedicated README file]].

* Emacs configuration

  I use the Emacs packages features to install and upgrade the packages that I
  use. They can come from ELPA, Melpa or Marmelade.

  The packages management (startup checking and installing) is inspired from
  https://github.com/kaushalmodi/.emacs.d/ Thanks to him.

  Another stuff, tips and tricks come from my colleagues or some blogs/websites
  as [[http://www.masteringemacs.org/][Mastering Emacs]], [[http://whattheemacsd.com/][What the emacs.d]], [[http://emacs-fu.blogspot.fr/][Emacs-fu]] or [[http://ergoemacs.org/emacs/][Xah Emacs]].

  For my own snippets (yasnippet package), I just make a symbolic link at
  =~/.emacs.d/snippets= to my =emacs/snippets= directory.

  See also [[https://github.com/garaud/foggycowinn/blob/master/emacs/README.org][README file for my Emacs config]].

* IPython

  Configuration files and different [[http://ipython.org/index.html][IPyhon]] profiles.

  See the [[https://github.com/garaud/foggycowinn/blob/master/ipython/README.rst][dedicated README file]].
