#+TITLE: README for Emacs Configuration
#+AUTHOR: Damien Garaud

* About

List of Emacs Lisp files for my own Emacs configuration.

* How to use it?
** Copy the FoggyCowInn Emacs directory

Do =git clone https://github.com/garaud/foggycowinn=.

See also on Gitorious at https://gitorious.org/foggycowinn

** Create or modify your Emacs configuration file

Take a look the the =.emacs.example= in the =emacs= directory.

The =emacs_init.el= is the main configuration file. It loads the different
files =foggy_*.el=.

** Emacs 24 or Emacs 23

I use Emacs 24 for a while now. These configuration should not work with
Emacs 23.

* Snippets

  I use =yasnippets= Emacs packages. I wrote some in the =emacs/snippets=
  directory. For now, I symlik =~/.emacs.d/snippets= to my =snippets=.

* Packages List

  See =emacs/foggy_packages-list.el=

* Turn me into a HTML/PDF file

  This operation requires the mode Org-mode --- http://orgmode.org/

  Open this file with Emacs and do:

  - =M-x org-export-as-pdf RET=
  - =M-x org-export-as-html RET=

  if you want to make a PDF --- via LaTeX --- or a HTML file.
